# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
#  - test
#  - build
  - security

include:
  - project: 'paydock/platform/gitlab-templates'
    ref: main
    file: '/security/gitlab-defectdojo.yaml'

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone

.macos_saas_runners:
  tags:
    - saas-macos-medium-m1
  image: macos-13-xcode-14

#test_exampleApp:
#  extends:
#    - .macos_saas_runners
#  stage: test
#  script:
##    - cd MobileSDK/
#    - bundle install
#    - bundle exec fastlane build_and_test device:'iPhone 14 Pro'
#  artifacts:
#    paths:
#      - MobileSDK/fastlane/test_output
#export_exampleApp:
#  extends:
#    - .macos_saas_runners
#  stage: build
#  script:
#    - cd ExampleApp/
#    - bundle install
#    - bundle exec fastlane archive_ci
#  artifacts:
#    paths:
#      - ExampleApp/fastlane/test_output
