disabled_rules:
  - line_length
  - function_body_length
  - nesting
  - identifier_name
  - large_tuple
  - todo
  - inclusive_language

identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length: 2

cyclomatic_complexity:
  warning: 25
  error: 30

file_length:
  warning: 600
  error: 1000

type_body_length:
  warning: 500
  error: 2000

function_parameter_count:
  warning: 10
  error: 15

type_name:
  max_length:
    warning: 60
    error: 100
  min_length:
    warning: 3
    error: 1
